import { Servicio } from '../es/services';

export const servicios: Servicio[] = [
  // Facial Procedures
  {
    id: 'rinoplastia',
    nombre: 'Rhinoplasty',
    subtitulo: 'Nose surgery to improve appearance and function, achieving facial harmony.',
    descripcion: 'Rhinoplasty is a nose surgery that seeks to improve the appearance and function of nasal structures, achieving harmony in the face. It can correct primary defects (present at birth) or secondary defects (acquired through trauma or previous surgeries). The procedure includes different techniques: closed rhinoplasty (without external incisions, ideal for minor defects), open rhinoplasty (with external incisions for better visibility, indicated for revision surgeries), septoplasty (corrects nasal septum problems) and turbinoplasty (improves respiratory function). It is generally performed on patients with aesthetic concerns or functional problems such as nasal hump, asymmetry, tip concerns, wide nasal wings, or breathing difficulties. The procedure lasts 2 to 4 hours, is performed under general anesthesia (or local with sedation in specific cases) and results are permanent. The patient can return to daily activities after one week, although the definitive result is appreciated after several weeks when the inflammatory process ends.',
    precioConsulta: 55,
    categoria: 'facial',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto-eng/images/RINO.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto-eng/images/RINO.jpg'
  },
  {
    id: 'frontoplastia',
    nombre: 'Forehead Lift',
    subtitulo: 'Rejuvenation of the upper third of the face through skin tightening.',
    descripcion: 'Forehead lift is a procedure designed to improve expression lines through skin tightening, generating a facial rejuvenation effect in the upper third of the face. This area is where the first signs of aging are most frequently evident, caused by photoaging, sun exposure, gravity, and hereditary factors. The procedure includes two main techniques: classic forehead lift (with incision in the scalp for soft tissue traction) and endoscopic forehead lift (with direct vision through an endoscope and small cuts in the muscles that generate expression lines). Ideal candidates are patients between 40 to 60 years old who seek to improve their appearance and self-esteem. Results will be seen long-term with skin without expression lines and tighter.',
    precioConsulta: 55,
    categoria: 'facial',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto-eng/images/FRONTO.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto-eng/images/FRONTO.jpg'
  },
  {
    id: 'blefaroplastia',
    nombre: 'Blepharoplasty',
    subtitulo: 'Eyelid surgery to remove excess skin and fat bags, improving facial appearance.',
    descripcion: 'Blepharoplasty can be performed on upper and lower eyelids to achieve a more youthful and fresh-looking face. This procedure consists of removing excess skin and fat bags, improving the appearance of the face altered by fat displacement to the lower part of the eyelid and dermal descent. There are two main techniques: traditional approach (with hidden incision in the natural fold of the upper eyelid and small cut in the lower eyelid) and transconjunctival approach (to remove fatty tissue from the lower eyelid through an incision on the inner side). This procedure is ideal for adult patients who manifest heaviness in the eyelids, bags in lower eyelids, marked expression lines, and aesthetic concerns. The procedure can take 1 to 3 hours, general anesthesia is used, and partial results will be seen in a few weeks when deflation reaches 90%, while final results could take 3 to 6 months.',
    precioConsulta: 55,
    categoria: 'facial',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://modelbell.es/wp-content/uploads/2025/09/blefaroplastia-superior-e-inferior.569Z-768x419.png',
    cardImageUrl: 'https://modelbell.es/wp-content/uploads/2025/09/blefaroplastia-superior-e-inferior.569Z-768x419.png'
  },
  {
    id: 'ritidoplastia',
    nombre: 'Facelift',
    subtitulo: 'Removal of excess facial skin to tighten the skin and improve facial angles.',
    descripcion: 'Through this procedure, excess skin in the facial region is removed, achieving skin tightening, improving facial angles, and attenuating expression lines generated by aging. This procedure does not stop aging or changes generated by exposure to environmental factors. Incisions are made in the scalp and on the edge of the auricular pavilion to disguise the incision site, improving facial angles by repositioning tissues, tightening the skin, and removing excess dermis. It is aimed at men and women, and can notably help young people who, for genetic reasons, present premature aging. The surgery is performed under general anesthesia and the patient can return to work activities in approximately 7 days. Results are long-term as long as dietary care, constant sun protection, and an exercise routine are maintained.',
    precioConsulta: 55,
    categoria: 'facial',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/RITIDO2.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/RITIDO2.jpg'
  },
  {
    id: 'cervicoplastia',
    nombre: 'Neck Lift',
    subtitulo: 'Cervicofacial lift to correct sagging skin under the jaw and improve mandibular contour.',
    descripcion: 'Neck lift, also known as cervicofacial lift, allows correcting sagging skin that has accumulated under the jaw, tightening the skin and underlying muscles to lift the neck, as well as improving and refining the mandibular contour. It is often performed in conjunction with a facial lift, but can also be performed as an independent procedure. Neck sagging generally occurs due to age, can be a result of significant weight loss, or hereditary reasons. A slim, thin neck with a defined jawline is a sign of youth and vitality. Over the years, these characteristics fade, fat accumulates in the neck giving that double chin, and muscle sagging occurs. This neck rejuvenation surgery can restore the brightness and youthful appearance of the face. Final results will appear in a few weeks when inflammation has decreased by at least 90%, but final results will take at least 2 to 6 months.',
    precioConsulta: 55,
    categoria: 'facial',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/cuello_recorte.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/cuello_recorte.jpg'
  },
  {
    id: 'bichectomia',
    nombre: 'Buccal Fat Removal',
    subtitulo: 'Removal of fat pads in the cheeks to refine facial features.',
    descripcion: 'Buccal fat removal is a surgical procedure in which the fat pads located at the lower edge of the cheeks are removed. These fat pads make the cheeks look more prominent. The most used technique is the internal or intraoral approach, which consists of making an incision in the oral mucosa at the upper part at the height of the second premolar. It requires local anesthesia and in very few cases requires stitches. Potential candidates are usually people with round faces or who wish to highlight the cheekbones to refine facial features, lengthen the face, and improve facial harmony. It is frequent in people with thin build who cannot slim their face despite exercise, sometimes caused by hereditary predisposition. This procedure decreases the round and wide appearance of the face, providing a thinner appearance naturally. Recovery time is short, 2 to 4 days, and one of the advantages is that there are no visible scars.',
    precioConsulta: 55,
    categoria: 'facial',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/bichectomia2.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/bichectomia2.jpg'
  },
  {
    id: 'mentoplastia',
    nombre: 'Chin Surgery',
    subtitulo: 'Chin surgery to improve facial aesthetic balance and facial harmony.',
    descripcion: 'The chin is part of the facial aesthetic balance that gives harmony to the face. In cases where there is a very marked decrease in the chin, chin surgery should be resorted to. This procedure can be given in combination with other surgeries, such as rhinoplasty, double chin liposuction, facelift, and blepharoplasty, among others, in order to give better symmetry to facial features. There are two main techniques: chin implant (with incision in the oral mucosa fold, placing a synthetic material implant that does not generate external scars) and chin lipoinjection (by aspirating adipose tissue from a body area and injecting it into the chin, dependent on weight gain or loss). The potential candidate is a patient who has finished their growth stage, who has some type of chin malformations, aesthetic concerns, some secondary alteration, or trauma. This surgery lasts approximately 1 hour, is performed with local anesthesia with sedation, is an outpatient procedure, painless and safe. Results will be visible immediately, but as inflammation decreases, they will look better.',
    precioConsulta: 55,
    categoria: 'facial',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/menton_2.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/menton_2.jpg'
  },
  {
    id: 'otoplastia',
    nombre: 'Otoplasty',
    subtitulo: 'Remodeling of the auricular pavilion to improve shape, position, or proportion of the ears.',
    descripcion: 'Otoplasty is the remodeling of the auricular pavilion. It can improve the shape, position, or proportion of the ears which are presented by structural, hereditary defects, or severe trauma, the procedure allows generating benefits to the appearance and self-esteem of the person. It is important to clarify that this surgery does not correct hearing problems or structures related to the middle and inner ear. There are two main types: prominent ear correction (to decrease the projection and angle of the auricular pavilion, removing cartilage at the auricular concha level) and microtia or anotia (intervention that begins with the extraction of costal cartilage from the patient to generate an auricular pavilion similar to normal). This is one of the aesthetic surgeries that can be performed from childhood, when development is complete around 6-8 years of age. However, a high percentage of adults come to have this type of intervention. Results for this type of intervention are immediate and will be visible once the dressings are removed and inflammation has subsided in a few weeks. This surgery can be complemented with other procedures such as blepharoplasty or eyebrow tail lift.',
    precioConsulta: 55,
    categoria: 'facial',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/otoplastia2.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/otoplastia2.jpg'
  },
  // Body Procedures
  {
    id: 'mamoplastia-aumento',
    nombre: 'Breast Augmentation',
    subtitulo: 'Increase in breast volume with implants to achieve symmetric and harmonious shape.',
    descripcion: 'Breast augmentation is a surgery that requires the use of implants that are placed under the glandular and muscular tissue. The purpose is to increase breast volume, give them a symmetric and harmonious shape to the breasts for aesthetic purposes, whether due to decreased development, changes after breastfeeding, or massive weight loss. Among the different types of implants are: saline solution (introduced without volume and filled with saline solution, allowing exact control of the final volume) and silicone (completely sealed, with fixed volume, guaranteeing more firmness to the breast, available in different shapes: round with low, medium, or high projection, or anatomical in teardrop shape). Surgeries are classified according to the type of incisions: axillary or transaxillary incision (in the middle part of the armpit) and lower areolar incision (around the lower part of the areola, the most used). Breast augmentation stylizes and gives special characteristics to the female silhouette, achieving a harmonious figure. Results are long-lasting but not permanent, as the decision can be made to remove the implants at any time.',
    precioConsulta: 55,
    categoria: 'corporal',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/MAMOAUMENTO.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/MAMOAUMENTO.jpg'
  },
  {
    id: 'mamoplastia-reduccion',
    nombre: 'Breast Reduction',
    subtitulo: 'Reduction of breast volume and breast lift (mastopexy).',
    descripcion: 'Factors such as breastfeeding, weight loss, and gravity cause breasts to alter their dimensions and location. It is normal for breast reduction to be accompanied by mastopexy, which is the technical name given to breast lift. This surgery also allows reducing the size of the areola to give a better visual effect to the breast. For this surgery, multiple surgical techniques can be used, the choice of which will depend on skin quality, breast volume, and areola size and position: areolar technique (when the drop is very mild, requires lifting 2 to 3 cm), vertical technique (when the drop and weight of the breast is greater) and inverted T technique (for patients with considerable volume, more invasive but achieves volume reduction and natural bust enhancement). It is aimed at women who want to reduce the volume of their bust, either because it causes back discomfort, after considerable weight loss, after breastfeeding, or all those who are not satisfied with their physical appearance. Estimated time for this procedure is 2 to 4 hours, with general anesthesia. Results are immediately visible and long-lasting, the new size will help alleviate back problems and pain.',
    precioConsulta: 55,
    categoria: 'corporal',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/reduccion.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/reduccion.jpg'
  },
  {
    id: 'liposuccion-lipoescultura',
    nombre: 'Liposuction / Body Contouring',
    subtitulo: 'Removal of localized body fat to shape the patient\'s silhouette.',
    descripcion: 'Normally liposuction is performed on the abdomen, hips, and thighs, although it can also be performed on other areas of the body such as arms, knees, ankles, double chin, buttocks, or face. The fundamental objective is to remove body fat in order to eliminate localized adiposity, cellulite, shape the patient\'s silhouette, and to a lesser extent reduce body weight. This procedure is not a treatment for obesity or overweight control. There are different techniques: conventional (application of liquids with vasoconstrictor directly to the fat), micro air PAL (Power Assisted Liposuction, with anteroposterior movements in the cannula), ultrasonic or Vaser (ultrasonic waves that break and emulsify fat, useful in areas with abundant fibrosis) and laser (laser lipolysis, which destroys adipocyte membranes). This surgery is designed for people who wish to eliminate fatty tissue, candidates who have tried to remove those fat deposits with exercise and diet without success, or who want to shape their body and have normal weight with elastic and firm skin. It is recommended to have 5 days to be able to return to work and personal activities.',
    precioConsulta: 55,
    categoria: 'corporal',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/lipo.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/lipo.jpg'
  },
  {
    id: 'lipectomia-abdominoplastia',
    nombre: 'Abdominoplasty',
    subtitulo: 'Removal of excess abdominal skin and fat with reinforcement of abdominal muscles.',
    descripcion: 'This surgical technique consists of making an incision above the pubis at the height of the lower abdominal fold, where excess skin and fat are lifted and removed. The abdominal muscles are reinforced, allowing a firmer appearance. This procedure allows removing unwanted tissue in the abdominal region which was obtained either due to weight loss, pregnancy, or hereditary conditions, among others. If you present skin sagging, stretch marks under the navel, and prominent abdomen, you are a candidate for this surgery. Generally, this procedure is performed on patients who, after being pregnant, are left with stretch marks, skin sagging, and marked abdominal weakness, and people who have had considerable weight loss, mostly after bariatric surgery. This surgery can last up to 3 hours and you can return to daily activities within 2 weeks. With this procedure, a defined waist is expected, improve the appearance of the navel, remove almost completely the stretch marks located in the lower abdomen, and tighten the skin in the abdominal region. Final and definitive results will be seen at 12 months of this procedure.',
    precioConsulta: 55,
    categoria: 'corporal',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/LIPECTOMIA.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/LIPECTOMIA.jpg'
  },
  {
    id: 'gluteoplastia',
    nombre: 'Buttock Augmentation',
    subtitulo: 'Increase and shaping of the buttock shape through implants or lipoinjection.',
    descripcion: 'Buttock lift can be performed through implant placement, leaving only a scar at the intergluteal fold level, or with gluteal lipoinjection which is performed through liposuction incisions. This procedure seeks to increase and shape the buttocks. There are two main types: gluteal lipoinjection (the fat extracted from liposuction is used to perform a volume increase in the buttocks, transferring approximately 300-350cc of fat in each buttock, has the advantage that there will be no rejection by the organism and results are more natural) and silicone implants (similar to breast implants but with special characteristics, larger and flattened, resembling the shape of the buttocks, used in people with little adipose tissue and poorly developed gluteal muscles). Buttock augmentation is indicated for patients who wish to improve the volume and projection of the gluteal region, or who find some disproportion in the shape of the buttocks. These procedures can last up to 2 hours and can be combined with body contouring in surrounding areas to better define the curvature of the buttocks. Partial results can be seen in a matter of weeks when bruising and inflammation decrease by 90%.',
    precioConsulta: 55,
    categoria: 'corporal',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/GLUTEO.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/GLUTEO.jpg'
  },
  {
    id: 'marcacion-abdomen',
    nombre: 'Abdominal Etching',
    subtitulo: 'Highlight the lateral and central marks of the abdomen to achieve defined abs.',
    descripcion: 'Having defined abs is the dream of many and this is an intervention that has made it stop being just a dream. This procedure allows highlighting the lateral and central marks of the abdomen. It is not a weight loss solution. It is usually used in people with a normal body mass index and whose diet and exercise routine have not allowed abdominal definition. This type of procedure is aimed at women and men who want to show a defined and marked abdomen and whose exercise routines and healthy lifestyle have not been enough to achieve it. This procedure is not advised to be performed on patients with overweight and obesity problems. The combination of body contouring in other areas will help achieve very good results that will be noticeable immediately, but as inflammation decreases, they will be noticed even more in a few weeks. It is not a permanent procedure and the patient must accept an exercise and diet routine that will help make the results lasting.',
    precioConsulta: 55,
    categoria: 'corporal',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/marcacion.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/marcacion.jpg'
  },
  {
    id: 'retiro-biopolimeros',
    nombre: 'Biopolymer Removal',
    subtitulo: 'Surgical extraction of harmful injectable substances that put health at risk.',
    descripcion: 'Biopolymers or Biogel are doses of liquid silicone that are injected into the facial or body region. In some cases, other materials are added to these substances that, when applied, the body encapsulates them, producing granulomas or lumps that cause severe inflammatory and immunological reactions, causing rejection of the product, which puts the integrity and life of patients at risk. These can only be extracted through surgery and there is no full guarantee that the extraction will be 100%. Biopolymers are banned worldwide due to the various problems that have occurred and the high number of victims it has left. The type of surgery depends primarily on several factors such as the amount of substance applied, the area, the type of material implanted, the reaction the body has produced, and the time that has elapsed, among others. In cases such as substances in the face, lips, and cheekbones, it is advisable to perform the extraction directly through one or several surgeries depending on the case. What is important in this type of surgery is the extraction of the largest amount of filler material. By extracting the compromised tissue and removing the invasive substances, the patient will no longer present inflammation or pain in the area.',
    precioConsulta: 55,
    categoria: 'corporal',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/RETIROBIOPOLIMEROS.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto/images/serviciosnuevos/RETIROBIOPOLIMEROS.jpg'
  },
  {
    id: 'rejuvenecimiento-vaginal',
    nombre: 'Vaginal Rejuvenation',
    subtitulo: 'Aesthetic and functional procedures to improve the appearance and sensitivity of the genitals.',
    descripcion: 'What this procedure seeks is to give a natural appearance to the genitals and correct those small imperfections that have become uncomfortable for the patient. It also allows improving sensitivity for women who desire a full sexual life. The widening of the vaginal introitus walls does not allow adequate friction, decreasing pleasure in sexual intercourse. With this intervention, characteristics of youth are improved, hymen recreation, and reduction of the mons pubis, among others. Conditions such as hypertrophy of the labia minora, majora, and their underdevelopment can be corrected. Clitoral surgery and vaginal tightening can also be performed. The vagina is reduced to only 3 cm in diameter, a standard measure established by surgeons, allowing increased pleasure for both parties. This procedure achieves rejuvenation and restoration of the aesthetic appearance of the vagina caused by childbirth, heredity, and dramatic weight loss. It is oriented to improve the quality of life of patients, allowing them to make decisions, improving their self-esteem, increasing confidence, and strengthening sexual appetite.',
    precioConsulta: 55,
    categoria: 'corporal',
    doctorIds: ['dr_pinto'],
    heroImageUrl: 'https://drfreddypinto.com.co/drpinto/images/REJUVAGINAL.jpg',
    cardImageUrl: 'https://drfreddypinto.com.co/drpinto/images/REJUVAGINAL.jpg'
  },
];
